"""empty message

Revision ID: 3d45a0499d30
Revises: 
Create Date: 2020-05-14 22:12:27.257105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d45a0499d30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=40), nullable=True),
    sa.Column('biography', sa.String(length=150), nullable=True),
    sa.Column('profile_picture', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
